mutants:
  data_access:
    dna_entries_key_prefix: "dna_entries:"
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  cache:
    type: redis
    redis:
      time-to-live: 3600000
    cache-names: result-stats
